### ISSUE TITLE
Role name incorrect in README.md for syslog-ng

### ISSUE THREAD

**Issue by jorneilander** [bodsch/ansible-collection-core#15]
The `README.md` starts with a loud and clear message that the role name is `syslog-ng`:

https://github.com/bodsch/ansible-collection-core/blob/0a595f754b78dcbd8121751ae840d74e739e9d74/roles/syslog_ng/README.md?plain=1#L2

While in fact it's actually called `syslog_ng` in accordance with the metadata:

https://github.com/bodsch/ansible-collection-core/blob/0a595f754b78dcbd8121751ae840d74e739e9d74/roles/syslog_ng/meta/main.yml#L3

**Comment by bodsch** [comment]
fixed with https://github.com/bodsch/ansible-collection-core/commit/64511883be965a29039d6ca1da811a4b0ef75d64
